### ISSUE TITLE
Sentence correction

### ISSUE THREAD

**Issue by goutamtadi1** [greenplum-db/docs#1]
Hi,

I was unsure if the statement attached in the [link](https://github.com/greenplum-db/docs/blob/4e117afb31f28a43216c33872876d02414af7d07/ref_guide/sql_commands/COPY.html#L5847) is right. Please discard if this is right.

**Comment by dyozie** [comment]
Thanks, Goutam - that sentence definitely has some stray words in it :-)  Will fix it.

**Comment by dyozie** [comment]
This fix is not in the source at https://github.com/greenplum-db/gpdb/blob/master/gpdb-doc/dita/ref_guide/sql_commands/COPY.xml#L388  HTML will be updated for the next beta release (probably in about a week).
